---

- name: "{{ task_prefix_pki }} | Init-CA | Getting CA password"
  ansible.builtin.include_tasks: instance/pwd_ca.yml

- name: "{{ task_prefix_pki }} | Init-CA | Adding CA-Owner"
  ansible.builtin.user:
    name: "{{ pki_cnf.owner }}"
    shell: '/bin/bash'
    comment: 'ansibleguy.infra_pki - owner of CA/PKI'
    state: present
  when: PKI.manage.users | bool

- name: "{{ task_prefix_pki }} | Init-CA | Adding CA-Groups"
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: ["{{ pki_cnf.group }}", "{{ pki_cnf.group_read }}"]
  when: PKI.manage.users | bool

- name: "{{ task_prefix_pki }} | Init-CA | Adding directory"
  ansible.builtin.file:
    path: "{{ pki_path_ca }}"
    state: directory
    owner: "{{ pki_cnf.owner }}"
    group: "{{ pki_cnf.group_read }}"
    mode: "{{ PKI_HC.mode.dir }}"

- name: "{{ task_prefix_pki }} | Init-CA | Copying from template"
  ansible.builtin.copy:
    src: "{{ PKI_TMPL }}/"
    remote_src: true
    dest: "{{ pki_path_ca }}/"
    owner: "{{ pki_cnf.owner }}"
    group: "{{ pki_cnf.owner }}"
    mode: "{{ PKI_HC.mode.file }}"
    directory_mode: "{{ PKI_HC.mode.dir }}"

- name: "{{ task_prefix_pki }} | Init-CA | Copying config"
  ansible.builtin.template:
    src: 'templates/var/local/lib/pki/instance/vars.j2'
    dest: "{{ pki_path_ca }}/vars"
    mode: "{{ PKI_HC.mode.file }}"
    owner: "{{ pki_cnf.owner }}"
    group: "{{ pki_cnf.owner }}"
  vars:
    easyrsa_vars: "{{ pki_vars }}"
    easyrsa_base: "{{ pki_path_ca }}"

- name: "{{ task_prefix_pki }} | Init-CA | Adding certificate extensions"
  ansible.builtin.template:
    src: 'templates/var/local/lib/pki/instance/x509-types/COMMON.j2'
    dest: "{{ pki_path_ca }}/x509-types/COMMON"
    mode: "{{ PKI_HC.mode.file }}"
    owner: "{{ pki_cnf.owner }}"
    group: "{{ pki_cnf.owner }}"
  vars:
    pki_crl_distribution: "{{ PKI.crl_distribution | combine(pki_cnf.crl_distribution) }}"
    pki_crl_prefix: 'ca'
    pki_extensions: "{{ PKI.extensions |
    combine(pki_cnf.extensions, recursive=true) }}"

- name: "{{ task_prefix_pki }} | Init-CA | Initializing"
  ansible.builtin.command: "{{ PKI_SCRIPT }} {{ pki_vars_param }} init-pki soft"
  changed_when: false
  environment:
    EASYRSA_PKI: "{{ pki_path_ca }}"

- name: "{{ task_prefix_pki }} | Init-CA | Generating CA"
  ansible.builtin.command: "{{ PKI_SCRIPT }} {{ pki_vars_param }} --no-text build-ca"
  changed_when: false
  environment:
    EASYRSA_PKI: "{{ pki_path_ca }}"
    EASYRSA_REQ_CN: "{{ pki_cnf.ca_cn }}"
    EASYRSA_PASSIN: "pass:{{ pki_ca_pwd }}"
    EASYRSA_PASSOUT: "pass:{{ pki_ca_pwd }}"
  no_log: true

- name: "{{ task_prefix_pki }} | Init-CA | Saving password"
  ansible.builtin.copy:
    dest: "{{ pki_path_ca }}/{{ PKI_HC.file.pwd_ca }}"
    content: "{{ pki_ca_pwd }}"
    mode: 0400  # if someone is already root - all hope is lost anyway
    owner: 'root'
    group: 'root'
  no_log: true
  when: PKI.save_passwords | bool

- name: "{{ task_prefix_pki }} | Init-CA | Generating CRL"
  ansible.builtin.include_tasks: instance/update_crl.yml
  vars:
    easyrsa_base: "{{ pki_path_ca }}"
    easyrsa_ca_pwd: "{{ pki_ca_pwd }}"
    crl_task_prefix: "{{ task_prefix_pki }}"

- name: "{{ task_prefix_pki }} | Init-CA | Updating privileges"
  ansible.builtin.include_tasks: instance/update_privileges.yml
  vars:
    easyrsa_base: "{{ pki_path_ca }}"
    privilege_task_prefix: "{{ task_prefix_pki }}"
  tags: [always]
  args:
    apply:
      tags: [always]
