---

- name: "{{ task_prefix_pki }} | PWD-CA | Checking if password-file is available"
  ansible.builtin.stat:
    path: "{{ pki_path_ca }}/{{ PKI_HC.file.pwd_ca }}"
  register: pki_ca_pwd_file
  when: PKI.save_passwords | bool

- name: "{{ task_prefix_pki }} | PWD-CA | Retrieving CA-password from file"
  ansible.builtin.command: "cat {{ pki_path_ca }}/{{ PKI_HC.file.pwd_ca }}"
  register: pki_ca_pwd_file
  changed_when: false
  no_log: true
  when:
    - PKI.save_passwords | bool
    - pki_ca_pwd_file.stat.exists

- name: "{{ task_prefix_pki }} | PWD-CA | Setting CA-password to saved one"
  ansible.builtin.set_fact:
    pki_ca_pwd: "{{ pki_ca_pwd_file.stdout }}"
  when:
    - PKI.save_passwords | bool
    - pki_ca_pwd_file.stat.exists

- name: "{{ task_prefix_pki }} | PWD-CA | Checking if CA-password was provided"
  ansible.builtin.set_fact:
    pki_ca_pwd: "{{ pki_cnf.pwd_ca }}"
  when: pki_cnf.pwd_ca | default(none, true) != none

- name: "{{ task_prefix_pki }} | PWD-CA | Prompting for CA-password"
  ansible.builtin.pause:
    prompt: "No CA password was provided! Please input one! MAKE SURE TO SAVE THIS PASSWORD!!"
    echo: false
  register: pki_ca_pwd_raw
  when: pki_ca_pwd is undefined
  delegate_to: localhost

- name: "{{ task_prefix_subca }} | PWD-CA | Debugging"
  ansible.builtin.debug:
    msg: "{{ hostvars['localhost'] }}"
  when:
    - pki_ca_pwd is undefined
    - "'pki_ca_pwd_raw' not in hostvars['localhost']"

- name: "{{ task_prefix_pki }} | PWD-CA | Setting CA-password to user-input"
  ansible.builtin.set_fact:
    pki_ca_pwd: "{{ hostvars['localhost'].pki_ca_pwd_raw.user_input }}"
  when: pki_ca_pwd is undefined

- name: "{{ task_prefix_pki }} | PWD-CA | Checking that password meets the requirements"
  ansible.builtin.assert:
    that:
      - pki_ca_pwd | meets_password_complexity(PKI_HC)
  tags: always
