---

- name: "{{ task_prefix_subca }} | Validating vars"
  ansible.builtin.include_tasks: validate_vars.yml
  vars:
    check_vars: "{{ pki_vars_subca }}"
    check_task_prefix: "{{ task_prefix_subca }}"

- name: "{{ task_prefix_subca }} | Checking if SubCA is initialized"
  ansible.builtin.stat:
    path: "{{ pki_path_subca }}/ca.crt"
  register: pki_subca_init

- name: "{{ task_prefix_subca }} | Initializing SubCA"
  ansible.builtin.include_tasks: init_subca.yml
  when: not pki_subca_init.stat.exists
