---

- name: "{{ task_prefix_subca }} | Validating vars"
  ansible.builtin.include_tasks: instance/validate_vars.yml
  vars:
    check_vars: "{{ pki_vars_subca }}"
    check_task_prefix: "{{ task_prefix_subca }}"

- name: "{{ task_prefix_subca }} | Getting SubCA password"
  ansible.builtin.include_tasks: instance/pwd_subca.yml
  tags: always
  args:
    apply:
      tags: always

- name: "{{ task_prefix_subca }} | Checking if SubCA is initialized"
  ansible.builtin.stat:
    path: "{{ pki_path_subca }}/{{ PKI_HC.file.ca }}"
  register: pki_subca_init
  tags: [certs, certs_renew, certs_create, certs_revoke]

- name: "{{ task_prefix_subca }} | Initializing SubCA"
  ansible.builtin.include_tasks: instance/init_subca.yml
  when: not pki_subca_init.stat.exists

- name: "{{ task_prefix_subca }} | Adding certificate extensions"
  ansible.builtin.template:
    src: 'templates/var/local/lib/pki/instance/x509-types/COMMON.j2'
    dest: "{{ pki_path_subca }}/x509-types/COMMON"
    mode: "{{ PKI_HC.mode.file }}"
    owner: "{{ pki_cnf.owner }}"
    group: "{{ pki_cnf.owner }}"
  vars:
    pki_crl_distribution: "{{ PKI.crl_distribution | combine(pki_cnf.crl_distribution) | combine(pki_cnf_subca.crl_distribution) }}"
    pki_crl_prefix: "subca_{{ pki_name_subca }}"
    pki_extensions: "{{ PKI.extensions |
    combine(pki_cnf.extensions, recursive=true) |
    combine(pki_cnf_subca.extensions, recursive=true) }}"

- name: "{{ task_prefix_subca }} | Processing certificates"
  ansible.builtin.include_tasks: instance/certs/main.yml
  when: pki_subca_init.stat.exists
  tags: [certs, certs_renew, certs_create, certs_revoke]
  args:
    apply:
      tags: [certs, certs_renew, certs_create, certs_revoke]

- name: "{{ task_prefix_subca }} | Updating privileges"
  ansible.builtin.include_tasks: instance/update_privileges.yml
  vars:
    easyrsa_base: "{{ pki_path_subca }}"
    privilege_task_prefix: "{{ task_prefix_subca }}"
  tags: always
  args:
    apply:
      tags: always
