---

- name: "{{ crl_task_prefix }} | Updating CRL"
  ansible.builtin.command: "{{ PKI_SCRIPT }} {{ pki_vars_param }} gen-crl"
  environment:
    EASYRSA_PKI: "{{ easyrsa_base }}"
    EASYRSA_PASSIN: "pass:{{ easyrsa_ca_pwd }}"
  no_log: true
