---

- name: PKI | EasyRSA | Checking if EasyRSA is downloaded (1/2)
  ansible.builtin.stat:
    path: "{{ PKI_TMPL }}"
  register: pki_easyrsa_tmpl

- name: PKI | EasyRSA | Checking if EasyRSA is downloaded (2/2)
  ansible.builtin.stat:
    path: "{{ PKI_SCRIPT }}"
  register: pki_easyrsa_script

- name: PKI | EasyRSA | Checking EasyRSA version
  ansible.builtin.command: "{{ PKI_SCRIPT }} --version"
  register: pki_easyrsa_version
  changed_when: false
  when:
    - pki_easyrsa_tmpl.stat.exists
    - pki_easyrsa_script.stat.exists

- name: PKI | EasyRSA | Downloading/Updating
  ansible.builtin.import_tasks: easyrsa_update.yml
  when: >
    not pki_easyrsa_tmpl.stat.exists or
    not pki_easyrsa_script.stat.exists or
    PKI.easyrsa_version not in pki_easyrsa_version.stdout
