---

- name: PKI | WORK IN PROGRESS
  ansible.builtin.fail:
    msg: "THIS ROLE IS STILL IN DEVELOPMENT! DO NOT USE!"
  tags: molecule-notest

- name: PKI | Checking config
  ansible.builtin.assert:
    that:
      - pki is defined
      - PKI.instances is defined
      - PKI.instances | length > 0
      - PKI.crl_distribution.domain is defined
      - PKI.crl_distribution.domain | valid_domain
      - PKI.crl_distribution.protocols | length > 0
      - PKI.mode_public | string in ['0644', '0640']

- name: PKI | Installing requirements
  ansible.builtin.package:
    name: "{{ PKI_HC.requirements }}"
    state: present

- name: PKI | EasyRSA
  ansible.builtin.import_tasks: easyrsa.yml

- name: PKI | Processing instances
  ansible.builtin.include_tasks: instance/main.yml
  vars:
    pki_name: "{{ pki_item.key | safe_key }}"
    pki_cnf: "{{ defaults_instance | combine(pki_item.value, recursive=true) }}"
    pki_vars: "{{ defaults_vars | 
    combine(defaults_vars_root_ca, recursive=true) | 
    combine(PKI.vars, recursive=true) | 
    combine(pki_vars, recursive=true) }}"
    pki_path_base: "{{ pki_cnf.path_base }}/{{ pki_name }}"
    pki_path_ca: "{{ pki_path_base }}/{{ PKI_HC.dir.root_ca }}"
    task_prefix_pki: "PKI | Instance '{{ pki_name }}'"
  loop_control:
    loop_var: pki_item
  with_dict: "{{ PKI.instances }}"
