---

- name: PKI | WORK IN PROGRESS
  ansible.builtin.fail:
    msg: "THIS ROLE IS STILL IN DEVELOPMENT! DO NOT USE!"

- name: PKI | Checking config
  ansible.builtin.assert:
    that:
      - pki is defined
      - PKI.instances is defined
      - PKI.instances | length > 0

- name: PKI | EasyRSA
  ansible.builtin.import_tasks: easyrsa.yml
  vars:
    path_tmpl: "{{ PKI_HC.easyrsa.path.template }}_{{ PKI.easyrsa_version }}"

- name: PKI | Processing instances
  ansible.builtin.include_tasks: instance/main.yml
  vars:
    pki_name: "{{ pki_item.key | safe_key }}"
    pki_cnf: "{{ defaults_instance | combine(pki_item.value, recursive=true) }}"
    pki_path_base: "{{ pki_cnf.path_base }}/{{ pki_name }}"
    pki_path: "{{ pki_path_base }}/pki"
  loop_control:
    loop_var: pki_item
  with_dict: "{{ PKI.instances }}"
