---

- name: PKI | Timezone | Getting local timezone
  ansible.builtin.shell: |
    set -o pipefail
    timedatectl | grep 'Time zone' | cut -d':' -f2 | cut -d' ' -f2
  register: pki_controller_tz
  delegate_to: localhost
  when: PKI.timezone | default(none, true) is none
  changed_when: false
  check_mode: false
  become: false
  args:
    executable: '/bin/bash'

- name: PKI | Timezone | Setting timezone on host
  community.general.timezone:
    name: "{{ PKI.timezone |
    default(pki_controller_tz.stdout, true) |
    default(PKI_HC.fallback_timezone, true) }}"
