---

- name: "{{ task_prefix_certs }} | '{{ pki_cert_name }}' | Exporting P{{ pki_export_p }}-Format"
  ansible.builtin.expect:
    command: "{{ PKI_SCRIPT }} {{ pki_vars_param }}
    export-p{{ pki_export_p }} {{ pki_cert_file }}
    {% if pki_cert_no_pass | bool %}nopass{% endif %}"
    responses:
      "Enter pass phrase": "{{ pki_cert_pwd }}"
      "Export Password": "{{ pki_cert_pwd }}"
      "Verify": "{{ pki_cert_pwd }}"
  environment:
    EASYRSA_PKI: "{{ pki_path_subca }}"
  args:
    creates: "{% if pki_export_p != '7' %}\
    {{ pki_path_subca }}/private/{{ pki_cert_file }}.p{{ pki_export_p }}\
    {% else %}\
    {{ pki_path_subca }}/issued/{{ pki_cert_file }}.p{{ pki_export_p }}b
    {% endif %}"
  no_log: true
