---

- name: "{{ task_prefix_subca }} | Certs | Checking config"
  ansible.builtin.assert:
    that:
      - pki_cnf_subca.certs | is_dict
  tags: always

# todo: pull existing certs to compare against config for purging

- name: "{{ task_prefix_subca }} | Certs | Processing certificate types"
  ansible.builtin.include_tasks: instance/certs/single.yml
  args:
    apply:
      tags: [certs, certs_renew, certs_create, certs_revoke]
  vars:
    pki_cert_type: "{{ pki_cert_type_item.key }}"
    pki_certs: "{{ pki_cert_type_item.value }}"
    task_prefix_certs: "{{ task_prefix_subca }} | Certs | {{ pki_cert_type }}"
  loop_control:
    loop_var: pki_cert_type_item
  with_dict: "{{ pki_cnf_subca.certs }}"
  no_log: true
