---

- name: "{{ task_prefix_certs }} | Checking config"
  ansible.builtin.assert:
    that:
      - pki_cert_type in PKI_HC.cert.types
      - pki_certs | is_dict
  tags: always

- name: "{{ task_prefix_certs }} | Processing certificates"
  ansible.builtin.include_tasks: instance/certs/state.yml
  vars:
    pki_cert_name: "{{ pki_cert_item.key | safe_key }}"
    pki_cert_cnf: "{{ defaults_cert | combine(pki_cert_item.value, recursive=true) }}"
    task_prefix_cert: "{{ task_prefix_certs }} | '{{ pki_cert_name }}'"
  loop_control:
    loop_var: pki_cert_item
  with_dict: "{{ pki_certs }}"
  no_log: true
