---

- name: Converge
  hosts: test-ag-infra_pki-1
  vars:
    pki:
      save_passwords: true
      crl_distribution:
        domain: 'crl.ansibleguy.net'

      instances:
        test1:
          pwd_ca: 'tesT12345'

          sub_cas:
            sub1:
              pwd_ca: 'tEst54321'
              certs:
                server:
                  ansibleguy_net:
                    cn: 'AnsibleGuy Website'
                    dns: ['www.ansibleguy.net', 'ansibleguy.net']
                    ip: ['135.181.170.217']

  roles:
    - ansibleguy.infra_pki
