---

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    pki_base: '/var/local/lib/pki'
    t1base: "{{ pki_base }}/test1"
    t1ca: "{{ t1base }}/ca"
    t1sub1: "{{ t1base }}/subca_sub1"
    t1sub2: "{{ t1base }}/subca_sub2"
    t2base: "{{ pki_base }}/test2"
    t2ca: "{{ t2base }}/ca"
    t2sub1: "{{ t2base }}/subca_sub1"
    owner: 'pki'
    owner2: 'pki2'
    group_read: 'pki_read'
    group_read2: 'pki_read2'

  tasks:
    - name: Performing backup
      ansible.builtin.systemd:
        name: 'backup-pki.service'
        state: started

    - name: Performing CRL-Update
      ansible.builtin.systemd:
        name: 'pki-crl-updater.service'
        state: started

    - name: Checking certificate existence
      ansible.builtin.stat:
        path: "{{ item }}"
      register: test_cert_file
      failed_when: not test_cert_file.stat.exists
      loop:
        # instance 1
        - "{{ t1ca }}/ca.crt"
        - "{{ t1ca }}/private/ca.key"
        ## sub-ca 1
        ### defaults
        - "{{ t1sub1 }}/ca.crt"
        - "{{ t1sub1 }}/private/ca.key"
        - "{{ t1sub1 }}/issued/server_test2.chain.crt"
        - "{{ t1sub1 }}/private/server_test2.p12"
        - "{{ t1sub1 }}/issued/server_test2.crt"
        - "{{ t1sub1 }}/private/server_test2.key"
        - "{{ t1sub1 }}/issued/client_wkst1.crt"
        - "{{ t1sub1 }}/private/client_wkst1.key"
        - "{{ t1sub1 }}/issued/email_guy.crt"
        - "{{ t1sub1 }}/private/email_guy.key"
        - "{{ t1sub1 }}/private/server_ansibleguynet.p12"
        - "{{ t1sub1 }}/issued/server_ansibleguynet.crt"
        - "{{ t1sub1 }}/private/server_ansibleguynet.key"
        ### custom configured
        - "{{ t1sub1 }}/private/server_ansibleguynet.unencrypted.key"
        # sub-ca 2
        ### defaults
        - "{{ t1sub2 }}/ca.crt"
        - "{{ t1sub2 }}/private/ca.key"
        - "{{ t1sub2 }}/issued/server_random1.crt"
        - "{{ t1sub2 }}/issued/server_random1.chain.crt"
        - "{{ t1sub2 }}/private/server_random1.key"
        - "{{ t1sub2 }}/private/server_random1.p12"
        ### custom configured
        # - "{{ t1sub2 }}/private/server_random1.p1"
        - "{{ t1sub2 }}/issued/server_random1.p7b"
        - "{{ t1sub2 }}/private/server_random1.p8"
        # instance 2
        - "{{ t2ca }}/ca.crt"
        - "{{ t2ca }}/private/ca.key"
        - "{{ t2sub1 }}/ca.crt"
        - "{{ t2sub1 }}/private/ca.key"
        # single
        - "{{ t1sub1 }}/issued/server_single.crt"
        - "{{ t1sub1 }}/issued/server_single.chain.crt"
        - "{{ t1sub1 }}/private/server_single.key"
        - "{{ t1sub1 }}/private/server_single.p12"
        - "{{ t1sub1 }}/private/server_single.unencrypted.key"

    - name: Checking certificate absence
      ansible.builtin.stat:
        path: "{{ item }}"
      register: test_cert_file
      failed_when: test_cert_file.stat.exists
      loop:
        # instance 1
        - "{{ t1sub1 }}/private/server_test2.p1"
        - "{{ t1sub1 }}/issued/server_test2.p7b"
        - "{{ t1sub1 }}/private/server_test2.p8"
        - "{{ t1sub1 }}/private/server_test2.unencrypted.key"
        # sub-ca 2
        - "{{ t1sub2 }}/private/server_random1.unencrypted.key"
        - "{{ t1sub2 }}/issued/serverClient_random2.chain.crt"
        - "{{ t1sub2 }}/private/serverClient_random2.p12"

    - name: Checking certificate content
      ansible.builtin.shell: |
        set -o pipefail
        openssl x509 -in {{ item.file }} -text | grep -q '{{ item.find }}'
      changed_when: false
      args:
        executable: '/bin/bash'
      with_items:
        # instance 1
        - {file: "{{ t1ca }}/ca.crt", find: 'Signature Algorithm: ecdsa-with-SHA512'}
        - {file: "{{ t1ca }}/ca.crt", find: 'ASN1 OID: secp384r1'}
        - {file: "{{ t1ca }}/ca.crt", find: 'CRL Distribution Points'}
        - {file: "{{ t1ca }}/ca.crt", find: 'URI:http://crl.ansibleguy.net/ca.crl'}
        - {file: "{{ t1ca }}/ca.crt", find: 'CA Issuers - URI:http://crl.ansibleguy.net/ca.crt'}
        - {file: "{{ t1ca }}/ca.crt", find: 'CA:TRUE'}
        - {file: "{{ t1ca }}/ca.crt", find: 'Subject: C = AT, ST = Styria, O = Ultra Company, OU = IT, CN = TestRootCA, emailAddress = pki@ansibleguy.net'}
        ## sub-ca 1
        - {file: "{{ t1sub1 }}/ca.crt", find: 'Signature Algorithm: ecdsa-with-SHA256'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'ASN1 OID: secp384r1'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'CRL Distribution Points'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'URI:http://crl.ansibleguy.net/ca.crl'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'CA Issuers - URI:http://crl.ansibleguy.net/ca.crt'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'CA:TRUE'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'Issuer: C = AT, ST = Styria, O = Ultra Company, OU = IT, CN = TestRootCA, emailAddress = pki@ansibleguy.net'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'Subject: C = AT, ST = Styria, L = Graz, O = Internal Org, CN = TestSubCA1, emailAddress = pki@ansibleguy.net'}
        - {file: "{{ t1sub1 }}/ca.crt", find: 'DirName:/C=AT/ST=Styria/O=Ultra Company/OU=IT/CN=TestRootCA/emailAddress=pki@ansibleguy.net'}
        - {file: "{{ t1sub1 }}/issued/server_test2.crt", find: 'Signature Algorithm: ecdsa-with-SHA256'}
        - {file: "{{ t1sub1 }}/issued/server_test2.crt", find: 'ASN1 OID: secp384r1'}
        - {file: "{{ t1sub1 }}/issued/server_test2.crt", find: 'CRL Distribution Points'}
        - {file: "{{ t1sub1 }}/issued/server_test2.crt", find: 'URI:http://crl.ansibleguy.net/subca_sub1.crl'}
        - {file: "{{ t1sub1 }}/issued/server_test2.crt", find: 'CA Issuers - URI:http://crl.ansibleguy.net/subca_sub1.crt'}
        - {file: "{{ t1sub1 }}/issued/server_ansibleguynet.crt",
           find: 'Subject: C = AT, ST = Styria, L = Graz, O = Internal Org, CN = AnsibleGuy Website, emailAddress = pki@ansibleguy.net'}
        - {file: "{{ t1sub1 }}/issued/server_ansibleguynet.crt",
           find: 'Issuer: C = AT, ST = Styria, L = Graz, O = Internal Org, CN = TestSubCA1, emailAddress = pki@ansibleguy.net'}
        - {file: "{{ t1sub1 }}/issued/server_ansibleguynet.crt",
           find: 'DNS:www.ansibleguy.net, DNS:ansibleguy.net, IP Address:135.181.170.217, URI:https://www.ansibleguy.net'}
        ## sub-ca 2
        - {file: "{{ t1sub2 }}/issued/server_random1.crt", find: 'URI:http://crl.ansibleguy.net/subca_sub2.crl'}
        - {file: "{{ t1sub2 }}/issued/server_random1.crt", find: 'CA Issuers - URI:http://crl.ansibleguy.net/subca_sub2.crt'}
        - {file: "{{ t1sub2 }}/issued/server_random1.crt", find: 'DNS:random.ansible.net'}
        - {file: "{{ t1sub2 }}/issued/serverClient_random2.crt",
           find: 'Subject: C = DE, ST = test2province, O = test2org, OU = test2ou, CN = ServerClientTest, emailAddress = test2email@test.intern'}
        - {file: "{{ t1sub2 }}/issued/serverClient_random2.crt", find: 'TLS Web Server Authentication, TLS Web Client Authentication'}

        # single
        - {file: "{{ t1sub1 }}/issued/server_single.crt", find: 'DNS:single.test, IP Address:192.168.0.1'}
        - {file: "{{ t1sub1 }}/issued/server_single.crt",
           find: 'Subject: C = AT, ST = Styria, L = Graz, O = test1org, CN = Single Certificate, emailAddress = pki@ansibleguy.net'}

    - name: Checking file/directory permissions (chmod)
      ansible.builtin.shell: |
        set -o pipefail
        ls -l {{ item.path }} | cut -d ' ' -f1
      changed_when: false
      args:
        executable: '/bin/bash'
      register: test_chmod
      failed_when: test_chmod.stdout_lines[1:] != item.expect
      with_items:
        - {path: "{{ t1sub1 }}", expect: [
          '-rw-r-----',
          '-rw-r-----',
          'drwxr-x---',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          'drwxr-x---',
          'drwxr-x---',
          '-rw-r-----',
          'drwxr-x---',
          'drwxr-x---',
          'drwxr-x---',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          'drwxr-x---',
        ]}
        - {path: "{{ t1sub1 }}/issued", expect: [
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
        ]}
        - {path: "{{ t1sub1 }}/private", expect: [
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
          '-rw-r-----',
        ]}

    - name: Checking file/directory ownership (chown)
      ansible.builtin.shell: |
        set -o pipefail
        ls -l {{ item.path }} | cut -d ' ' -f{{ item.fields }}
      changed_when: false
      args:
        executable: '/bin/bash'
      register: test_chown
      failed_when: test_chown.stdout_lines[1:] != item.expect
      with_items:
        - {path: "{{ t1sub1 }}", fields: '3-4', expect: [
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
        ]}
        - {path: "{{ t1sub1 }}/private", fields: '3-4', expect: [
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
          "{{ owner }} {{ owner }}",
        ]}
        - {path: "{{ t1sub1 }}/issued", fields: '3-4', expect: [
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
          "{{ owner }} {{ group_read }}",
        ]}
        - {path: "{{ t2sub1 }}/private", fields: '3-4', expect: [
          "{{ owner2 }} {{ owner2 }}",
        ]}
        - { path: "{{ t2base }}", fields: '3-4', expect: [
          "{{ owner2 }} {{ group_read2 }}",
          "{{ owner2 }} {{ group_read2 }}",
        ] }
